import { Platform, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#000",
  },
  containerForm: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 2,
    backgroundColor: "#000",
    position: "absolute",
    top: 20,
    width: "100%",
    height: 910,
  },
  containerHeader: {
    marginLeft: 30,
    flex: 1,
    flexDirection: "row",
    justifyContent: "flex-start",
    marginTop: 80,
    width: "100%",
    borderBottomWidth: 0.2,
    borderBottomColor: "#ccc",
    borderColor: "#ccc",
    maxHeight: 50,
  },
  imgHeader: {
    width: 30,
    height: 30,
  },
  tituloInfo: {
    fontSize: 26,
    color: "#EC5D0A",
    fontWeight: "bold",
    marginLeft: 100,
  },
  login: {},
  containerLogin: {
    flex: 1,
    alignItems: "center",
    marginTop: 70,
  },
  textoLogin: {
    fontSize: 28,
    color: "#fff",
    marginBottom: 40,
  },
  textoInput: {
    color: "#2A2A2A",
  },
  form: {
    flex: 1,
    alignItems: "center",
  },
  input: {
    width: 300,
    height: 50,
    color: "#fff",
    fontSize: 16,
    marginTop: 20,
    borderBottomWidth: 2,
    borderBottomColor: "#2A2A2A",
    borderColor: "#2A2A2A",
  },
  btnLogin: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 5,
    marginTop: 40,
    width: 300,
    maxHeight: 50,
    borderWidth: 2,
    borderBottomWidth: 2,
    borderRadius: 30,
    borderColor: "#2A2A2A",
  },
  textoBtnLogin: {
    color: "#2A2A2A",
    fontSize: 22,
  },
  nav: {
    marginTop: 0,
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    width: 200,
  },
  pipe: {
    color: "#fff",
    width: 10,
    marginLeft: 5,
  },
  opcao: {
    color: "#EC5D0A",
    fontWeight: "bold",
  },
});
